[package]
name = "client"
version = "0.1.0"
authors = ["VictoremWinbringer <victor@mail.ru>"]
edition = "2018"

[dependencies]
text_io = "*"
azul = { git = "https://github.com/maps4print/azul" }
backtrace = "*"